#!/bin/bash

brew install \
  neovim \
  mas \
  tmux \
  starship \
  fzf \
  eza \
  dsully/tap/macos-defaults \
  fd \
  zsh \
  awscli \
  go \
  graphviz \
  lua \
  terraform \
  zoxide \
  xh \
  gh \
  git \
  bat \
  caddy \
  pgcli \
  ripgrep \
  FelixKratz/formulae/borders \
  delta \
  lazygit \
  stow

brew install --cask \
  raycast \
  karabiner-elements \
  1password 1password-cli \
  font-fira-code-nerd-font \
  vivaldi \
  nikitabobko/tap/aerospace \
  orbstack \
  istat-menus \
  notion-calendar

mas install \
  747648890 `# Telegram` \
  803453959 `# Slack` \
  1569813296 `# 1Password for Safari` \
  310633997 `# WhatsApp` \
  1480933944 `# Vimari` \
  1607635845 `# Velja`

if [ ! -d ~/.tmux/plugins/tpm ]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

sudo-touchid
