#!/bin/bash

set -e

./bootstrap/links
./bootstrap/installations

macos-defaults apply ./macos-defaults
/System/Library/PrivateFrameworks/SystemAdministration.framework/Resources/activateSettings -u

# ./bootstrap/homebrew

# brew install homebrew/cask-fonts/font-fira-code-nerd-font

# command: (ls /Library/Fonts/Source\ Code\ Pro* &>/dev/null) || (git clone https://github.com/powerline/fonts.git --depth=1 __powerline_fonts__ && (cd __powerline_fonts__ && cp -v SourceCodePro/*.otf /Library/Fonts/) && rm -rf __powerline_fonts__)
# description: Installing powerline fonts

# command: "(ls ~/.vim/autoload/plug.vim &> /dev/null) || (mkdir -p ~/.vim/autoload && curl -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim)"
# description: Install Vundle.vim, if necessary

# command: "vim +PlugInstall +PlugUpdate +qall"
# description: Update vim plugins
# stdout: true

# command: pip3 install -U neovim
