"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = "$character"

[character] # The name of the module we are configuring is "character"
success_symbol = "[⛧](bold blue)"
error_symbol = "[⛧](bold red)"
