set-option -g status on
set -s escape-time 0
set-option -g status-interval 15
set-option -g status-utf8 on
set-option -g status-justify "centre"
set-option -g status-left-length 60
set-option -g status-right-length 90
set-option -g status-left "#(~/Code/tmux-powerline/powerline.sh left)"
set-option -g status-right "#(~/Code/tmux-powerline/powerline.sh right)"
set-window-option -g window-status-current-format "#[fg=colour14, bg=colour0, bold] [#I] #W "
set-window-option -g window-status-format "#[fg=colour235, bg=colour0]#[fg=colour255, bg=colour0] [#I] #W #[fg=colour27, bg=colour0]"
set-option -g status-position top
set-option -g status-bg colour0
set -g default-terminal "screen-256color"
